/**
 * Fix Consultant Names Script
 *
 * This script:
 * 1. Connects to the test.Client collection
 * 2. Finds all tickets with "Auto-generated" consultant names
 * 3. Updates them with the correct consultant name from the Client database
 * 4. Shows which emails don't have matching clients
 *
 * Run: node server/scripts/fixConsultantNames.js
 */
require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const mongoose = require('mongoose');

async function fixConsultantNames() {
  console.log('\n🔧 ====== FIX CONSULTANT NAMES SCRIPT ======\n');

  // Connect to main database
  const mongoUri = process.env.MONGO_URI || 'mongodb://localhost:27017/slidexpress';
  console.log('📦 Connecting to main database...');
  console.log(`   URI: ${mongoUri.replace(/\/\/[^:]+:[^@]+@/, '//***:***@')}`);

  await mongoose.connect(mongoUri);
  console.log('✅ Connected to main database\n');

  // Import the Client helper (connects to test database)
  const { findClientByEmail, getClientModel, getClientName, findClientsByEmails } = require('../models/Client');
  const Ticket = require('../models/Ticket');

  // Test connection to test.Client collection
  console.log('🔌 Testing connection to test.Client collection...');
  let clientCount = 0;
  try {
    const ClientModel = await getClientModel();
    clientCount = await ClientModel.countDocuments();
    console.log(`✅ Connected to test.Client collection (${clientCount} clients found)\n`);

    // Show sample clients
    const sampleClients = await ClientModel.find({}).limit(3).lean();
    console.log('📋 Sample clients in test.Client:');
    sampleClients.forEach(c => {
      const derivedName = getClientName(c);
      console.log(`   • Email: "${c['Email']}" | Client: "${derivedName}" | Consultant: "${c['Consultant Name']}"`);
    });
    console.log('');
  } catch (err) {
    console.error('❌ Failed to connect to test.Client:', err.message);
    console.log('\n💡 Make sure the test database exists and has a Client collection');
    await mongoose.disconnect();
    return;
  }

  // Get all tickets
  const tickets = await Ticket.find({}).lean();
  console.log(`📋 Found ${tickets.length} tickets to check\n`);

  // Stats
  let fixedAutoGenerated = 0;
  let updatedFromClient = 0;
  let noClientMatch = 0;
  let alreadyCorrect = 0;
  const unmatchedEmails = new Set();

  // Get unique client emails from tickets
  const ticketEmails = [...new Set(tickets.map(t => t.clientEmail?.toLowerCase()).filter(Boolean))];
  console.log(`🔍 Looking up ${ticketEmails.length} unique client emails...\n`);

  // Batch lookup all clients
  const clients = await findClientsByEmails(ticketEmails);

  // Create email -> client lookup map
  const clientMap = {};
  clients.forEach(c => {
    if (c['Email']) {
      const key = c['Email'].toLowerCase();
      clientMap[key] = c;
    }
  });

  console.log(`👥 Found ${clients.length} matching clients in test.Client\n`);
  console.log('─'.repeat(60));

  for (const ticket of tickets) {
    const clientEmail = ticket.clientEmail?.toLowerCase();
    const currentConsultant = ticket.consultantName || '';

    if (!clientEmail) {
      continue;
    }

    const client = clientMap[clientEmail];

    if (client) {
      const rawConsultantName = client['Consultant Name'];
      const dbConsultantName = (typeof rawConsultantName === 'string') ? rawConsultantName.trim() : '';
      const dbClientName = getClientName(client);  // Account Name (company name)

      // Check if update needed
      const needsConsultantUpdate = currentConsultant !== dbConsultantName;
      const needsClientNameUpdate = ticket.clientName !== dbClientName &&
                                    dbClientName !== '' &&
                                    dbClientName.toLowerCase() !== 'no name';

      if (needsConsultantUpdate || needsClientNameUpdate) {
        const updates = {};
        if (needsConsultantUpdate) updates.consultantName = dbConsultantName;
        if (needsClientNameUpdate) updates.clientName = dbClientName;

        await Ticket.updateOne(
          { _id: ticket._id },
          { $set: updates }
        );

        if (currentConsultant === 'Auto-generated') {
          console.log(`🔧 ${ticket.jobId}: Fixed "Auto-generated" → "${dbConsultantName || '(blank)'}"`);
          fixedAutoGenerated++;
        } else if (needsClientNameUpdate) {
          console.log(`✅ ${ticket.jobId}: Updated Client: "${ticket.clientName}" → "${dbClientName}"`);
          updatedFromClient++;
        } else {
          console.log(`✅ ${ticket.jobId}: Updated Consultant: "${currentConsultant}" → "${dbConsultantName || '(blank)'}"`);
          updatedFromClient++;
        }
      } else {
        alreadyCorrect++;
      }
    } else {
      // No matching client found
      unmatchedEmails.add(clientEmail);

      // Clear "Auto-generated" if present
      if (currentConsultant === 'Auto-generated') {
        await Ticket.updateOne(
          { _id: ticket._id },
          { $set: { consultantName: '' } }
        );
        console.log(`🧹 ${ticket.jobId}: Cleared "Auto-generated" (no client match for ${clientEmail})`);
        fixedAutoGenerated++;
      } else {
        noClientMatch++;
      }
    }
  }

  console.log('─'.repeat(60));
  console.log('\n📊 ====== SUMMARY ======');
  console.log(`   ✅ Already correct: ${alreadyCorrect}`);
  console.log(`   🔧 Fixed "Auto-generated": ${fixedAutoGenerated}`);
  console.log(`   📝 Updated from Client DB: ${updatedFromClient}`);
  console.log(`   ⚠️  No client match: ${noClientMatch}`);

  if (unmatchedEmails.size > 0) {
    console.log(`\n⚠️  Emails without matching client in test.Client (${unmatchedEmails.size}):`);
    [...unmatchedEmails].slice(0, 10).forEach(email => {
      console.log(`   • ${email}`);
    });
    if (unmatchedEmails.size > 10) {
      console.log(`   ... and ${unmatchedEmails.size - 10} more`);
    }
    console.log('\n💡 To add these clients, add them to the test.Client collection with:');
    console.log('   - Email (the email address)');
    console.log('   - Client Name');
    console.log('   - Consultant Name');
  }

  console.log('\n=============================\n');

  await mongoose.disconnect();
  console.log('🔌 Disconnected from databases');
}

fixConsultantNames().catch(err => {
  console.error('❌ Script error:', err);
  process.exit(1);
});
